import { f, OPTIONS, type CollectionDef } from './schema.js';

export const noteFolders: CollectionDef = {
  name: 'noteFolders',
  label: 'Note folders',
  singular: 'Folder',
  icon: 'folder',
  area: 'life',
  scope: 'system',
  titleField: 'name',
  sortField: 'sortOrder',
  sortDir: 'asc',
  fields: [
    f.text('name', 'Name', { required: true, inList: true, searchable: true }),
    f.color('color', 'Colour'),
    f.text('icon', 'Symbol', { maxLength: 8 }),
    f.ref('parentId', 'Inside folder', 'noteFolders'),
    f.int('sortOrder', 'Order', { defaultValue: 0 }),
  ],
};

export const notes: CollectionDef = {
  name: 'notes',
  label: 'Notes',
  singular: 'Note',
  icon: 'note',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'title',
  sortField: 'updatedAt',
  sortDir: 'desc',
  indexes: [['systemId', 'folderId']],
  fields: [
    f.text('title', 'Title', { inList: true, searchable: true }),
    f.long('body', 'Note', { searchable: true }),
    f.ref('folderId', 'Folder', 'noteFolders', { inList: true }),
    f.tags('tags', 'Tags'),
    f.json('checklist', 'Checklist', { hint: 'Items with a label and a done flag.' }),
    f.refs('attachmentIds', 'Attachments', 'mediaItems'),
    f.bool('pinned', 'Pinned', { inList: true }),
    f.bool('archived', 'Archived'),
    f.color('color', 'Colour'),
  ],
};

export const tasks: CollectionDef = {
  name: 'tasks',
  label: 'Tasks',
  singular: 'Task',
  icon: 'task',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'title',
  sortField: 'dueAt',
  sortDir: 'asc',
  indexes: [['systemId', 'completed', 'dueAt']],
  fields: [
    f.text('title', 'Task', { required: true, inList: true, searchable: true }),
    f.long('notes', 'Notes', { searchable: true }),
    f.datetime('dueAt', 'Due', { inList: true }),
    f.enumOf('priority', 'Priority', OPTIONS.priority, { defaultValue: 'normal', inList: true }),
    f.text('category', 'Category', { inList: true, searchable: true }),
    f.bool('completed', 'Completed', { inList: true }),
    f.datetime('completedAt', 'Completed at'),
    f.json('subtasks', 'Subtasks'),
    f.text('recurrence', 'Repeats', { hint: 'daily, weekly, monthly, weekdays, or none.' }),
    f.datetime('remindAt', 'Reminder'),
    f.bool('remindSent', 'Reminder sent'),
    f.tags('tags', 'Tags'),
    f.bool('archived', 'Archived'),
    f.bool('forWholeSystem', 'For the whole system', { defaultValue: true }),
  ],
};

export const calendarEvents: CollectionDef = {
  name: 'calendarEvents',
  label: 'Calendar',
  singular: 'Event',
  icon: 'calendar',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'title',
  sortField: 'startsAt',
  sortDir: 'asc',
  indexes: [['systemId', 'startsAt']],
  fields: [
    f.text('title', 'Title', { required: true, inList: true, searchable: true }),
    f.long('notes', 'Notes', { searchable: true }),
    f.datetime('startsAt', 'Starts', { required: true, inList: true }),
    f.datetime('endsAt', 'Ends'),
    f.bool('allDay', 'All day'),
    f.text('location', 'Location', { searchable: true }),
    f.refs('memberIds', 'Members involved', 'members'),
    f.color('color', 'Colour'),
    f.text('recurrence', 'Repeats'),
    f.datetime('remindAt', 'Reminder'),
    f.bool('remindSent', 'Reminder sent'),
    f.refs('attachmentIds', 'Attachments', 'mediaItems'),
    f.enumOf('kind', 'Kind', [
      { value: 'personal', label: 'Personal' },
      { value: 'system', label: 'System' },
      { value: 'work', label: 'Work' },
      { value: 'health', label: 'Health' },
      { value: 'social', label: 'Social' },
      { value: 'birthday', label: 'Birthday' },
    ], { defaultValue: 'personal', inList: true }),
  ],
};

export const mediaItems: CollectionDef = {
  name: 'mediaItems',
  label: 'Media library',
  singular: 'Media item',
  icon: 'media',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'title',
  sortField: 'createdAt',
  sortDir: 'desc',
  indexes: [['systemId', 'mediaType']],
  fields: [
    f.text('title', 'Title', { inList: true, searchable: true }),
    f.enumOf('mediaType', 'Type', [
      { value: 'image', label: 'Image', icon: '▣' },
      { value: 'video', label: 'Video', icon: '▶' },
      { value: 'audio', label: 'Audio', icon: '♪' },
      { value: 'document', label: 'Document', icon: '▤' },
    ], { required: true, defaultValue: 'image', inList: true }),
    f.url('url', 'File', { required: true }),
    f.url('thumbnailUrl', 'Thumbnail'),
    f.text('mimeType', 'MIME type'),
    f.int('sizeBytes', 'Size'),
    f.int('width', 'Width'),
    f.int('height', 'Height'),
    f.int('durationSeconds', 'Duration'),
    f.long('description', 'Description', { searchable: true }),
    f.text('folder', 'Folder', { inList: true, searchable: true }),
    f.tags('tags', 'Tags'),
    f.text('source', 'Source'),
    f.bool('favorite', 'Favourite', { inList: true }),
    f.bool('pinned', 'Pinned'),
    f.bool('inVault', 'Keep in vault'),
    f.json('focalPoint', 'Focal point'),
  ],
};

export const moodEntries: CollectionDef = {
  name: 'moodEntries',
  label: 'Moods',
  singular: 'Mood',
  icon: 'mood',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'label',
  sortField: 'recordedAt',
  sortDir: 'desc',
  indexes: [['systemId', 'recordedAt']],
  fields: [
    f.text('label', 'Mood', { required: true, inList: true, searchable: true }),
    f.int('score', 'Score', { min: 1, max: 10, inList: true, hint: '1 lowest — 10 highest.' }),
    f.datetime('recordedAt', 'When', { required: true, inList: true }),
    f.long('note', 'Note', { searchable: true }),
    f.tags('tags', 'Tags'),
    f.color('color', 'Colour'),
  ],
};

export const emotionEntries: CollectionDef = {
  name: 'emotionEntries',
  label: 'Emotions',
  singular: 'Emotion entry',
  icon: 'emotion',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'emotionId',
  sortField: 'recordedAt',
  sortDir: 'desc',
  indexes: [['systemId', 'recordedAt'], ['systemId', 'emotionId']],
  fields: [
    f.text('emotionId', 'Emotion', { required: true, inList: true, searchable: true }),
    f.text('category', 'Category', { inList: true }),
    f.int('intensity', 'Intensity', { min: 1, max: 5, defaultValue: 3, inList: true }),
    f.datetime('recordedAt', 'When', { required: true, inList: true }),
    f.text('context', 'Context', { searchable: true, hint: 'What was happening.' }),
    f.long('note', 'Note', { searchable: true }),
    f.tags('tags', 'Tags'),
    f.text('activity', 'Activity', { searchable: true }),
  ],
};

export const bodySensations: CollectionDef = {
  name: 'bodySensations',
  label: 'Body sensations',
  singular: 'Sensation',
  icon: 'body',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'sensation',
  sortField: 'recordedAt',
  sortDir: 'desc',
  description: 'Somatic tracking. A log, not an assessment.',
  fields: [
    f.text('region', 'Body area', { required: true, inList: true }),
    f.text('sensation', 'Sensation', { required: true, inList: true, searchable: true }),
    f.int('intensity', 'Intensity', { min: 1, max: 5, defaultValue: 3, inList: true }),
    f.datetime('recordedAt', 'When', { required: true, inList: true }),
    f.long('note', 'Note', { searchable: true }),
    f.enumOf('side', 'Side', [
      { value: 'both', label: 'Both' },
      { value: 'left', label: 'Left' },
      { value: 'right', label: 'Right' },
      { value: 'centre', label: 'Centre' },
    ], { defaultValue: 'both' }),
  ],
};

export const wellnessEntries: CollectionDef = {
  name: 'wellnessEntries',
  label: 'Wellbeing',
  singular: 'Wellbeing check-in',
  icon: 'wellbeing',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'recordedAt',
  sortField: 'recordedAt',
  sortDir: 'desc',
  fields: [
    f.datetime('recordedAt', 'When', { required: true, inList: true }),
    f.int('energy', 'Energy', { min: 1, max: 10, inList: true }),
    f.int('stress', 'Stress', { min: 1, max: 10, inList: true }),
    f.int('comfort', 'Comfort', { min: 1, max: 10 }),
    f.int('hydrationGlasses', 'Water (glasses)', { min: 0, max: 40 }),
    f.int('mealCount', 'Meals', { min: 0, max: 20 }),
    f.int('painLevel', 'Physical discomfort', { min: 0, max: 10 }),
    f.int('socialBattery', 'Social battery', { min: 1, max: 10 }),
    f.bool('medicationTaken', 'Medication taken'),
    f.long('note', 'Note', { searchable: true }),
    f.json('customMetrics', 'Custom metrics', {
      hint: 'Metrics the system defined for itself.',
    }),
    f.tags('tags', 'Tags'),
  ],
};

export const sleepEntries: CollectionDef = {
  name: 'sleepEntries',
  label: 'Sleep',
  singular: 'Sleep entry',
  icon: 'sleep',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'startedAt',
  sortField: 'startedAt',
  sortDir: 'desc',
  indexes: [['systemId', 'startedAt']],
  fields: [
    f.datetime('startedAt', 'Fell asleep', { required: true, inList: true }),
    f.datetime('endedAt', 'Woke up', { inList: true }),
    f.int('durationMinutes', 'Duration', { inList: true }),
    f.int('quality', 'Quality', { min: 1, max: 5, inList: true }),
    f.bool('isNap', 'Nap'),
    f.int('awakenings', 'Times awake', { min: 0, max: 50 }),
    f.text('mood', 'Mood on waking'),
    f.long('dreamNotes', 'Dreams', { searchable: true }),
    f.long('note', 'Note', { searchable: true }),
    f.tags('tags', 'Tags'),
  ],
};

export const fitnessEntries: CollectionDef = {
  name: 'fitnessEntries',
  label: 'Fitness',
  singular: 'Activity',
  icon: 'fitness',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'activity',
  sortField: 'performedAt',
  sortDir: 'desc',
  description: 'Movement you choose to record. No targets are assumed and nothing is scored.',
  fields: [
    f.text('activity', 'Activity', { required: true, inList: true, searchable: true }),
    f.datetime('performedAt', 'When', { required: true, inList: true }),
    f.int('durationMinutes', 'Duration', { inList: true }),
    f.real('distanceKm', 'Distance (km)'),
    f.int('steps', 'Steps'),
    f.int('intensity', 'Effort', { min: 1, max: 5 }),
    f.long('note', 'Note', { searchable: true }),
    f.text('goalKey', 'Goal'),
    f.tags('tags', 'Tags'),
  ],
};

export const cycleEntries: CollectionDef = {
  name: 'cycleEntries',
  label: 'Cycle & wellness',
  singular: 'Cycle entry',
  icon: 'cycle',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'phase',
  sortField: 'entryDate',
  sortDir: 'desc',
  neverPublic: true,
  description:
    'A configurable cycle log. Every field is optional and the phases are whatever the user names them.',
  fields: [
    f.date('entryDate', 'Date', { required: true, inList: true }),
    f.text('phase', 'Phase', { inList: true, hint: 'Your own labels — nothing is preset.' }),
    f.enumOf('eventType', 'Event', [
      { value: 'none', label: 'No event' },
      { value: 'start', label: 'Cycle start' },
      { value: 'end', label: 'Cycle end' },
      { value: 'symptom', label: 'Symptom day' },
      { value: 'note', label: 'Note only' },
    ], { defaultValue: 'none', inList: true }),
    f.tags('symptoms', 'Symptoms'),
    f.int('energy', 'Energy', { min: 1, max: 10 }),
    f.int('discomfort', 'Discomfort', { min: 0, max: 10 }),
    f.text('mood', 'Mood'),
    f.long('note', 'Note', { searchable: true }),
    f.bool('remind', 'Remind me next cycle'),
  ],
};

export const financeAccounts: CollectionDef = {
  name: 'financeAccounts',
  label: 'Accounts',
  singular: 'Account',
  icon: 'finance',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'name',
  sortField: 'name',
  sortDir: 'asc',
  neverPublic: true,
  fields: [
    f.text('name', 'Name', { required: true, inList: true, searchable: true }),
    f.enumOf('kind', 'Type', [
      { value: 'checking', label: 'Everyday' },
      { value: 'savings', label: 'Savings' },
      { value: 'cash', label: 'Cash' },
      { value: 'credit', label: 'Credit' },
      { value: 'other', label: 'Other' },
    ], { defaultValue: 'checking', inList: true }),
    f.money('openingBalance', 'Opening balance', { defaultValue: 0 }),
    f.text('currency', 'Currency', { defaultValue: 'USD', maxLength: 8 }),
    f.color('color', 'Colour'),
    f.long('notes', 'Notes'),
    f.bool('archived', 'Archived'),
  ],
};

export const transactions: CollectionDef = {
  name: 'transactions',
  label: 'Transactions',
  singular: 'Transaction',
  icon: 'finance',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'description',
  sortField: 'occurredAt',
  sortDir: 'desc',
  indexes: [['systemId', 'occurredAt'], ['systemId', 'accountId']],
  neverPublic: true,
  fields: [
    f.text('description', 'Description', { required: true, inList: true, searchable: true }),
    f.money('amount', 'Amount', { required: true, inList: true, hint: 'Negative for spending.' }),
    f.datetime('occurredAt', 'Date', { required: true, inList: true }),
    f.ref('accountId', 'Account', 'financeAccounts', { inList: true }),
    f.text('category', 'Category', { inList: true, searchable: true }),
    f.enumOf('kind', 'Kind', [
      { value: 'expense', label: 'Expense' },
      { value: 'income', label: 'Income' },
      { value: 'transfer', label: 'Transfer' },
    ], { defaultValue: 'expense', inList: true }),
    f.text('recurrence', 'Repeats'),
    f.long('notes', 'Notes', { searchable: true }),
    f.tags('tags', 'Tags'),
  ],
};

export const budgets: CollectionDef = {
  name: 'budgets',
  label: 'Budgets',
  singular: 'Budget',
  icon: 'finance',
  area: 'life',
  scope: 'system',
  titleField: 'category',
  sortField: 'category',
  sortDir: 'asc',
  neverPublic: true,
  fields: [
    f.text('category', 'Category', { required: true, inList: true, searchable: true }),
    f.money('limitAmount', 'Monthly limit', { required: true, inList: true }),
    f.text('period', 'Period', { defaultValue: 'monthly' }),
    f.color('color', 'Colour'),
    f.long('notes', 'Notes'),
  ],
};

export const savingsGoals: CollectionDef = {
  name: 'savingsGoals',
  label: 'Savings goals',
  singular: 'Goal',
  icon: 'finance',
  area: 'life',
  scope: 'system',
  titleField: 'name',
  sortField: 'targetDate',
  sortDir: 'asc',
  neverPublic: true,
  fields: [
    f.text('name', 'Goal', { required: true, inList: true, searchable: true }),
    f.money('targetAmount', 'Target', { required: true, inList: true }),
    f.money('savedAmount', 'Saved so far', { defaultValue: 0, inList: true }),
    f.date('targetDate', 'Target date'),
    f.color('color', 'Colour'),
    f.long('notes', 'Notes'),
  ],
};

export const contacts: CollectionDef = {
  name: 'contacts',
  label: 'Contacts',
  singular: 'Contact',
  icon: 'contact',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'name',
  sortField: 'name',
  sortDir: 'asc',
  neverPublic: true,
  fields: [
    f.text('name', 'Name', { required: true, inList: true, searchable: true }),
    f.text('nickname', 'Nickname', { searchable: true }),
    f.text('relationship', 'Relationship', { inList: true, searchable: true }),
    f.text('phone', 'Phone', { sensitive: true }),
    f.text('email', 'Email', { sensitive: true }),
    f.json('socialLinks', 'Social links'),
    f.enumOf('safety', 'Safety', OPTIONS.safety, { defaultValue: 'unset', inList: true }),
    f.bool('currentlyWith', 'Currently with them', { inList: true }),
    f.datetime('lastInteractionAt', 'Last interaction'),
    f.refs('knownByMemberIds', 'Known by', 'members'),
    f.long('notes', 'Notes', { searchable: true, sensitive: true }),
    f.tags('tags', 'Tags'),
    f.image('avatarUrl', 'Photo'),
  ],
};

export const emergencyContacts: CollectionDef = {
  name: 'emergencyContacts',
  label: 'Emergency contacts',
  singular: 'Emergency contact',
  icon: 'emergency',
  area: 'life',
  scope: 'system',
  titleField: 'name',
  sortField: 'priority',
  sortDir: 'asc',
  neverPublic: true,
  description: 'Kept out of every public surface and every notification preview.',
  fields: [
    f.text('name', 'Name', { required: true, inList: true }),
    f.text('relationship', 'Relationship', { inList: true }),
    f.text('phone', 'Phone', { inList: true, sensitive: true }),
    f.text('email', 'Email', { sensitive: true }),
    f.int('priority', 'Priority', { defaultValue: 1, min: 1, max: 20, inList: true }),
    f.text('availability', 'Availability', { hint: 'When they can usually be reached.' }),
    f.long('notes', 'Notes', { sensitive: true }),
  ],
};

export const locationEntries: CollectionDef = {
  name: 'locationEntries',
  label: 'Locations',
  singular: 'Location',
  icon: 'location',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  titleField: 'name',
  sortField: 'visitedAt',
  sortDir: 'desc',
  neverPublic: true,
  description: 'Places recorded by hand. Nothing is captured automatically unless explicitly enabled.',
  fields: [
    f.text('name', 'Place', { required: true, inList: true, searchable: true }),
    f.datetime('visitedAt', 'When', { required: true, inList: true }),
    f.text('activity', 'Activity', { inList: true, searchable: true }),
    f.long('note', 'Note', { searchable: true }),
    f.real('latitude', 'Latitude', { sensitive: true }),
    f.real('longitude', 'Longitude', { sensitive: true }),
    f.text('address', 'Address', { sensitive: true }),
    f.tags('tags', 'Tags'),
    f.bool('favorite', 'Favourite'),
  ],
};

export const vaultItems: CollectionDef = {
  name: 'vaultItems',
  label: 'Private vault',
  singular: 'Vault item',
  icon: 'vault',
  area: 'life',
  scope: 'system',
  memberScoped: true,
  vault: true,
  neverPublic: true,
  titleField: 'title',
  sortField: 'updatedAt',
  sortDir: 'desc',
  description: 'Requires an unlocked vault session on the server for every read and write.',
  fields: [
    f.text('title', 'Title', { required: true, inList: true }),
    f.enumOf('kind', 'Kind', [
      { value: 'note', label: 'Note' },
      { value: 'journal', label: 'Journal entry' },
      { value: 'document', label: 'Document' },
      { value: 'media', label: 'Media' },
      { value: 'credential', label: 'Reference' },
    ], { defaultValue: 'note', inList: true }),
    f.long('body', 'Contents', { sensitive: true }),
    f.url('url', 'File', { sensitive: true }),
    f.tags('tags', 'Tags'),
    f.color('color', 'Colour'),
  ],
};

export const LIFE_COLLECTIONS = [
  noteFolders,
  notes,
  tasks,
  calendarEvents,
  mediaItems,
  moodEntries,
  emotionEntries,
  bodySensations,
  wellnessEntries,
  sleepEntries,
  fitnessEntries,
  cycleEntries,
  financeAccounts,
  transactions,
  budgets,
  savingsGoals,
  contacts,
  emergencyContacts,
  locationEntries,
  vaultItems,
] as const;
